application: twittan-dm
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /_ah/mail/xxxx@.*twittan-dm\.appspotmail\.com
  script: handle_dm.py
  login: admin

- url: /
  static_files: public/index.html
  upload: public/index.html
